# Generated by Django 5.0.6 on 2024-06-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descriptipn',
            new_name='description',
        ),
    ]
