# Generated by Django 5.0.6 on 2024-06-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_coursemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseManager',
        ),
    ]
