# Generated by Django 5.0.6 on 2024-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_auther', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
